on:
  push:
    branches: [ master ]
  schedule:
  - cron: "20 12 * * fri"
  workflow_dispatch:
    branches: [main, master]

name: Render-presentation

jobs:
  render-rmarkdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-renv@v2

      - name: Execute Script
        run: |
          Rscript "inst/render-rmd.R"
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add docs/index.Rmd
          git add docs/index.html
          git add inst/rmarkdown/templates/apresenta-o-r-ladies/skeleton/skeleton.Rmd
          git add inst/rmarkdown/templates/apresenta-o-r-ladies/skeleton/custom.css
          git add inst/rmarkdown/templates/apresenta-o-r-ladies/skeleton/libs/remark-latest.min.js
          git commit -m 'Re-build docs/index.Rmd' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
