on:
  push:
    branches: [ master ]
  schedule:
  - cron: "20 12 * * fri"
  workflow_dispatch:
    branches: [main, master]

name: Render-presentation


jobs:
  render:

    name: Render-presentation

    runs-on: ubuntu-18.04

    env:
      RSPM: "https://packagemanager.rstudio.com/all/__linux__/bionic/latest"
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1

      - name: Install pak and query dependencies
        run: |
          install.packages("pak", repos = "https://r-lib.github.io/p/pak/dev/")
          saveRDS(pak::pkg_deps("local::.", dependencies = TRUE), ".github/r-depends.rds")
        shell: Rscript {0}

      - name: Restore R package cache
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.R_LIBS_USER }}/*
            !${{ env.R_LIBS_USER }}/pak
          key: ${{ matrix.config.os }}-${{ steps.install-r.outputs.installed-r-version }}-1-${{ hashFiles('.github/r-depends.rds') }}
          restore-keys: ${{ matrix.config.os }}-${{ steps.install-r.outputs.installed-r-version }}-1-

      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: |
          pak::local_system_requirements(execute = TRUE)
          pak::pkg_system_requirements("rcmdcheck", execute = TRUE)
        shell: Rscript {0}

      - name: Install dependencies
        run: |
          pak::local_install_dev_deps(upgrade = TRUE)
          pak::local_install(".")
        shell: Rscript {0}


      - name: Execute Script
        run: |
          Rscript "inst/render-rmd.R"
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add docs/index.Rmd
          git add docs/index.html
          git add .github/r-depends.rds
          git add inst/rmarkdown/templates/apresenta-o-r-ladies/skeleton/skeleton.Rmd
          git add inst/rmarkdown/templates/apresenta-o-r-ladies/skeleton/custom.css
          git add inst/rmarkdown/templates/apresenta-o-r-ladies/skeleton/libs/remark-latest.min.js
          git commit -m 'Re-build docs/index.Rmd' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
